# Generated by Django 6.0.1 on 2026-01-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LibraryConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fine_per_day",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        help_text="Fine amount per day for overdue books.",
                        max_digits=5,
                    ),
                ),
                (
                    "hold_expiry_days",
                    models.PositiveIntegerField(
                        default=3,
                        help_text="Number of days a reserved book is held before being released.",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
