# Generated by Django 6.0.1 on 2026-01-14 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_alter_book_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="status",
            field=models.CharField(
                choices=[
                    ("AVAILABLE", "Available"),
                    ("OUT_OF_STOCK", "Out of Stock"),
                    ("RESERVED", "Reserved"),
                    ("LOST", "Lost"),
                ],
                default="AVAILABLE",
                max_length=20,
            ),
        ),
    ]
