# Generated by Django 6.0.1 on 2026-01-10 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MembershipTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("max_books", models.PositiveIntegerField(default=2)),
                ("borrow_duration_days", models.PositiveIntegerField(default=14)),
                (
                    "subscription_fee",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="is_active_member",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="membership_tier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.membershiptier",
            ),
        ),
    ]
