# Generated by Django 6.0.1 on 2026-01-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_membershiptier_user_is_active_member_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="membershiptier",
            name="max_renewals",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
