# Generated by Django 6.0.1 on 2026-01-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("circulation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="borrowrecord",
            name="renewal_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
